layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

bio: "I enjoy reading, growing various plants, listening to classical/post-rock music and podcasts. I also love playing Violin.
"

about: "I'm Negar, a fifth year Ph.D. candidate at <a href=\"https://uci.edu/\">the University of Calirofnia, Irvine</a>. As a member of <a href=\"https://www.ics.uci.edu/~seal/index.html\">SEAL</a> Lab, I'm working under supervision of <a href=\"https://www.ics.uci.edu/~malek/\">Dr. Sam Malek</a> and <a href=\"https://jgarcia.ics.uci.edu\">Dr. Joshua Garcia</a>. My research interests are in software engineering with a focus on software analysis and testing, machine learning for automated software engineering, and software security.
"

email: negargh@uci.edu

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  scholar: E3yGWDsAAAAJ
  linkedin: negar-ghorbani-13625251
  github: negarq
  # mastodon: your_username
  # medium: noidsirius
  # stackoverflow: 2681272/noidsirius
  # telegram: your_username
  twitter: negarq
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

work:
  - company: "University of California, Irvine"
    company_url: "http://seal.ics.uci.edu/"
    role: "Graduate Research Assistant"
    start: "September 2016"
    end: "Present"
    description: "<ul class='text-gray mb-2 ws-normal pl-3'>
      <li> Conducting research in the areas of Software Engineering, Program Analysis, Software Testing, and Mobile Apps Security Under supervision of Dr. Sam Malek and Dr. Joshua Garcia </li>
    </ul>"
  - company: "Microsoft Research, Data & AI Applied Science"
    company_url: "https://www.microsoft.com/en-us/research/"
    role: "Applied Scientist"
    start: "March 2021"
    end: "Present"
    description: "<ul class='text-gray mb-2 ws-normal pl-3'>
      <li> Conducting research in the areas of Machine Learning for Automated Software Engineering </li>
    </ul>"
  - company: "Fujitsu Laboratories of America, Sunnyvale, CA"
    company_url: "https://www.fujitsu.com/us/about/businesspolicy/tech/rd/"
    role: "Software Engineering Research Intern"
    start: "June 2020"
    end: "September 2020"
    description: "<ul class='text-gray mb-2 ws-normal pl-3'>
      <li> Mining and fixing software bugs using crowd intelligence and unsupervised machine learning </li>
    </ul>"
  - company: "Morgan Stanley, New York, NY"
    company_url: "https://www.morganstanley.com"
    role: "Software Engineering Intern"
    start: "June 2019"
    end: "September 2019"
    description: "<ul class='text-gray mb-2 ws-normal pl-3'>
      <li> Designing and developing dynamic and static optimization methods in a framework for distributed and parallelized graph based calculations in Scala. </li>
    </ul>"
  - company: "Institute for Studies in Theoretical Physics and Mathematics (IPM), Tehran, Iran"
    company_url: ""
    role: "Research Assistant"
    start: "June 2015"
    end: "July 2016"
    description: "<ul class='text-gray mb-2 ws-normal pl-3'>
      <li> Modeling and Evaluation of Service Composition in Commercial Multi-Clouds using Timed Colored Petri Nets. </li>
    </ul>"
  - company: "Pishtazan Andishe Pouya, Tehran, Iran"
    company_url: ""
    role: "Software Engineering Intern"
    start: "January 2016"
    end: "July 2016"
    description: "<ul class='text-gray mb-2 ws-normal pl-3'>
      <li> Design and analysis of models for software information systems and web applications. </li>
    </ul>"
  - company: "VADA Future Communications,Tehran, Iran"
    company_url: ""
    role: "Software Developer"
    start: "January 2014"
    end: "December 2014"
    description: "<ul class='text-gray mb-2 ws-normal pl-3'>
      <li> Designed, developed, and maintained mobile and web applications. </li>
    </ul>"


publication:
  - name: "Forecasting Architectural Decay from Evolutionary History"
    authors: "Joshua Garcia, Ehsan Kouroshfar, <u>Negar Ghorbani</u>, Sam Malek"
    conference: "IEEE Transactions on Software Engineering, 2021"
    pdf: "https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9357984"
  - name: "Flair: Efficient Analysis of Android Inter-Component Vulnerabilities in Response to Incremental Changes"
    authors: "Hamid Bagheri, Jianghao Wang, Jarod Aerts, <u>Negar Ghorbani</u>, and Sam Malek"
    conference: "Empirical Software Engineering (EMSE), 2021"
  - name: "Detection and repair of architectural inconsistencies in Java"
    authors: "<u>Negar Ghorbani</u>, Joshua Garcia, Sam Malek"
    conference: "<strong>ICSE 2019</strong>, IEEE/ACM 41st International Conference on Software Engineering, Montreal, QC, Canada, May 2019, 21% acceptance rate"
    repo: "https://github.com/seal-hub/darcy-artifact"
    pdf: "https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=8812079"
    html_url: "https://www.ics.uci.edu/~seal/projects/darcy/index.html"
  - name: "A temporal permission analysis and enforcement framework for android"
    authors: "Alireza Sadeghi, Reyhaneh Jabbarvand, <u>Negar Ghorbani</u>, Hamid Bagheri, Sam Malek"
    conference: "<strong>ICSE 2018</strong>, IEEE/ACM 40th International Conference on Software Engineering, Gothenburg, Sweden, May 2018, 21% acceptance rate"
    pdf: "https://dl.acm.org/doi/pdf/10.1145/3180155.3180172"
    html_url: "https://www.ics.uci.edu/~seal/projects/terminator/index.html"
  - name: "Automatic generation of inter-component communication exploits for Android applications"
    authors: "Joshua Garcia, Mahmoud Hammad, <u>Negar Ghorbani</u>, Sam Malek"
    conference: "<strong>FSE 2017</strong>, ACM SIGSOFT Symposium on the Foundations of Software Engineering (ESEC/FSE), Paderborn, Germany, September 2017, 21% acceptance rate"
    pdf: "https://dl.acm.org/doi/pdf/10.1145/3106237.3106286"
    html_url: "https://www.ics.uci.edu/~seal/projects/letterbomb/index.html"
  - name: "Modeling and Evaluation of Service Composition in Commercial Multi-Clouds using Timed Colored Petri Nets"
    authors: "Reza Entezari-Maleki, Sayed Ehsan Etesami, <u>Negar Ghorbani</u>, Arian Akhavan Niaki, Leonel Sousa, Ali Movaghar"
    conference: "IEEE Transactions on Systems, Man, and Cybernetics: Systems, 2017"
    pdf: "https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=8116749"



  # - name: Ben ;
  #  video: https://youtu.be/eSkozhtT-9o
    # pdf: http://seal.ics.uci.edu/publications/2020_MobiSys_BenchERoid.pdf

    # pdf: http://seal.ics.uci.edu/publications/2020_ASE_Empirical.pdf

  # - name: B
  #   description: A Static Analysis Framework for Accurate and Scalable Event-Race Detection in Android
  #   html_url: https://github.com/seal-hub/ERCatcher
  #
  # - name: C
  #   description: A Micro-Benchmark for Event Races in Android
  #   html_url: https://github.com/seal-hub/bencheroid


projects:
  - name: Darcy
    description: An approach that leverages static program analyses to automatically detect architectural inconsistencies within Java applications and repair them. 
    html_url: https://github.com/seal-hub/darcy-artifact
    source: github





topics:
  - name: Java

  - name: Program Analysis

  - name: Software Analysis and Testing

  - name: Machine Learning for Automated Software Engineering

  # - name: CSS
  #   web_url: https://github.com/topics/css
  #   image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png
  #   description: I learned something I learned something I learned something I learned something

  # - name: Web design

  # - name: Sass
  #   web_url: https://github.com/topics/sass
  #   image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png